site_name: IEX DOWNLOAD
docs_dir: docs
nav:
  - Overview: index.md

theme:
  name: material
  custom_dir: docs/overrides
  highlightjs: true
  features:
    - navigation.instant <- messes up mathjax, keep it disabled!
    - search.suggest
    - content.code.copy
  icon:
  admonition:
  palette:
    - scheme: solarized
      primary: orange
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - scheme: slate
      primary: orange
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
extra:
  social:
    - icon: simple/x
      link: https://x.com/vargaconsulting 
    - icon: simple/reddit
      link: https://www.reddit.com/user/vargaconsulting/submitted/
    - icon: simple/substack
      link: https://substack.com/@vargaconsulting
    - icon: simple/medium
      link: https://medium.com/@steven.varga      
    - icon: fontawesome/brands/github
      link: https://github.com/orgs/vargaconsulting/repositories
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/steven-varga-04224a19/
  icons:
    - material
    - fontawesome/brands
    - fontawesome/solid
  analytics:
    provider: google
    property: G-QC2C4XW904
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - tables
  - footnotes
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg  
  - pymdownx.tabbed:
      alternate_style: true  
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.blocks.caption
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde  
  - pymdownx.critic
  - pymdownx.keys
    
extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdn.jsdelivr.net/npm/asciinema-player@3.0.1/dist/bundle/asciinema-player.js
  - javascripts/mathjax.js

extra_css:
  - styles/custom.css
  - https://cdn.jsdelivr.net/npm/asciinema-player@3.0.1/dist/bundle/asciinema-player.css
