site_name: VargaLABS
site_url: https://steven-varga.ca
site_description: IEX-DOWNLOAD — Fast Access to the Full IEX Historical Market Feed (TOPS, DEEP & DEEP+) since 2017
site_author: Steven Varga
copyright: Steven Varga
docs_dir: docs
twitter_handle: "@vargaconsulting"
nav:
  - Overview: index.md
plugins:
  - search
theme:
  name: material
  custom_dir: docs/overrides
  features:
    - navigation.instant #<- messes up mathjax, keep it disabled!
    - search.suggest
    - content.code.copy
    - content.tooltips    
  icon:
  admonition:
  palette:
    - scheme: solarized
      primary: orange
      toggle:
        icon: moon
        name: Switch to dark mode
    - scheme: slate
      primary: orange
      toggle:
        icon: sun
        name: Switch to light mode
extra:
  social:
    - icon: material/whatsapp
      link: https://wa.me/16475611829
    - icon: material/email-fast
      link: mailto:steven@vargaconsulting.ca
    - icon: material/twitter
      link: https://x.com/vargaconsulting
    - icon: material/linkedin
      link: https://www.linkedin.com/in/steven-varga-04224a19/
    - icon: material/github 
      link: https://github.com/vargaconsulting

  analytics:
    provider: google
    property: G-L58Z6SZ3TN
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - tables
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg  
  - pymdownx.tabbed:
      alternate_style: true  
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.blocks.caption
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde  
  - pymdownx.critic
  - pymdownx.keys
  - pymdownx.snippets:
      base_path:
        - docs/blog/specs
        - docs/blog/examples
        - docs/blog/posts
        - docs/blog/pics
        - docs/blog/data
        - docs/blog/scripts
        - docs/blog/casts
  
extra_javascript:
  - javascripts/mathjax.js
  - javascripts/mathjax-tex-mml-chtml.js
  - javascripts/tailwind.js
  - javascripts/tw-config.js
  - javascripts/asciinema-player.min.js
  - javascripts/alpine.js
  - javascripts/popper.js
  - javascripts/tippy.js

extra_css:
  - styles/asciinema-player.css
  - styles/asciinema.css
  - styles/animate.css
  - styles/custom.css
  - styles/mobile.css
  - styles/socials.css
  - styles/background.css
  - styles/blog.css