site_name: VargaLABS
site_url: https://steven-varga.ca
site_description: Advanced Systems for Trading, Cryptography, and Data Engineering
site_author: Steven Varga
copyright: Steven Varga
docs_dir: docs
twitter_handle: "@vargaconsulting"
nav:
  - IEX-DOWNLOAD: index.md

plugins:
  - search
theme:
  name: material
  custom_dir: docs/overrides
  features:
    #- navigation.instant #<- messes up mathjax, keep it disabled!
    - search.suggest
    - content.code.copy
    - content.tooltips    
  icon:
  admonition:
  palette:
    - scheme: solarized
      primary: orange
      toggle:
        icon: moon
        name: Switch to dark mode
    - scheme: slate
      primary: orange
      toggle:
        icon: sun
        name: Switch to light mode
extra:
  social:
    - icon: material/whatsapp
      link: https://wa.me/16475611829
    - icon: material/email-fast
      link: mailto:steven@vargaconsulting.ca
    - icon: material/twitter
      link: https://x.com/vargaconsulting
    - icon: material/linkedin
      link: https://www.linkedin.com/in/steven-varga-04224a19/
    - icon: material/github 
      link: https://github.com/vargaconsulting

  analytics:
    provider: google
    property: G-QC2C4XW904
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - tables
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg  
  - pymdownx.tabbed:
      alternate_style: true  
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.blocks.caption
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde  
  - pymdownx.critic
  - pymdownx.keys
  - pymdownx.snippets:
      base_path:
        - docs/blog/specs
        - docs/blog/examples
        - docs/blog/posts
        - docs/blog/pics
        - docs/blog/data
        - docs/blog/scripts
        - docs/blog/casts
  
extra_javascript:
  - javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdn.tailwindcss.com 
  - javascripts/tw-config.js   
  - https://cdn.jsdelivr.net/npm/asciinema-player@3.0.1/dist/bundle/asciinema-player.js
  - https://unpkg.com/alpinejs@3.14.9/dist/cdn.min.js
  - https://unpkg.com/@popperjs/core@2
  - https://unpkg.com/tippy.js@6

extra_css:
  - https://cdn.jsdelivr.net/npm/asciinema-player@3.0.1/dist/bundle/asciinema-player.css
  - https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css
  - styles/custom.css
  - styles/mobile.css
  - styles/socials.css  
  - styles/background.css
  - styles/blog.css
  - styles/asciinema.css
